name: CI

on:

  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]


  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3

    - name: Testing Actions
      run: echo Hello, world!

    - id: "auth"
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: Criando e populando .env
      run: |
        touch .env
        echo API_KEY=${{ secrets.API_KEY }} >> .env
        echo API_URL=${{ secrets.API_URL }} >> .env
        echo PORT=${{ secrets.PORT }} >> .env

    - name: "Install dependencies"
      run: npm install

    - id: "deploy"
      uses: "google-github-actions/deploy-appengine@v1"